<?= $this->extend('layouts/main'); ?>

<?php $this->section('content'); ?>

<div class="container mt-4">
    <div class="card shadow-sm p-4">
        <h2 class="card-title text-center mb-4"><?= esc($title) ?></h2>

        <?php if (session()->getFlashdata('success')): ?>
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <?= session()->getFlashdata('success') ?>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        <?php endif; ?>
        <?php if (session()->getFlashdata('error')): ?>
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <?= session()->getFlashdata('error') ?>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        <?php endif; ?>

        <!-- Display validation errors if they exist -->
        <?php if (session()->getFlashdata('errors')): ?>
            <div class="alert alert-danger">
                <ul>
                    <?php foreach (session()->getFlashdata('errors') as $error): ?>
                        <li><?= esc($error) ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>

        <form action="<?= base_url('e-way-bills/store') ?>" method="post">
            <?= csrf_field() ?>

            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="distributor_sales_order_id" class="form-label">Sales Order Invoice Number</label>
                    <select class="form-control" id="distributor_sales_order_id" name="distributor_sales_order_id" required>
                        <option value="">Select an Invoice</option>
                        <?php foreach ($sales_orders as $order): ?>
                            <option value="<?= esc($order['id']) ?>" <?= set_select('distributor_sales_order_id', $order['id']) ?>>
                                <?= esc($order['invoice_number']) ?> - <?= esc($order['agency_name']) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>

                <div class="col-md-6 mb-3">
                    <label for="bill_generated_by" class="form-label">Bill Generated By</label>
                    <input type="text" class="form-control" id="bill_generated_by" name="bill_generated_by" value="<?= set_value('bill_generated_by') ?>" required>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="place_of_dispatch" class="form-label">Place of Dispatch</label>
                    <input type="text" class="form-control" id="place_of_dispatch" name="place_of_dispatch" value="<?= set_value('place_of_dispatch') ?>" required>
                </div>
                <div class="col-md-6 mb-3">
                    <label for="place_of_delivery" class="form-label">Place of Delivery</label>
                    <input type="text" class="form-control" id="place_of_delivery" name="place_of_delivery" value="<?= set_value('place_of_delivery') ?>" required>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="driver_name" class="form-label">Driver Name</label>
                    <input type="text" class="form-control" id="driver_name" name="driver_name" value="<?= set_value('driver_name') ?>" required>
                </div>
                <div class="col-md-6 mb-3">
                    <label for="vehicle_number" class="form-label">Vehicle Number</label>
                    <input type="text" class="form-control" id="vehicle_number" name="vehicle_number" value="<?= set_value('vehicle_number') ?>" required>
                </div>
            </div>

            <!-- New fields added -->
            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="distance" class="form-label">Valid Distance (in KM)</label>
                    <input type="number" class="form-control" id="distance" name="distance" value="<?= set_value('distance') ?>" required>
                </div>
                <div class="col-md-6 mb-3">
                    <label for="transport_mode" class="form-label">Transport Mode</label>
                    <select class="form-control" id="transport_mode" name="transport_mode" required>
                        <option value="">Select Transport Mode</option>
                        <option value="Road" <?= set_select('transport_mode', 'Road') ?>>Road</option>
                        <option value="Rail" <?= set_select('transport_mode', 'Rail') ?>>Rail</option>
                        <option value="Air" <?= set_select('transport_mode', 'Air') ?>>Air</option>
                        <option value="Ship" <?= set_select('transport_mode', 'Ship') ?>>Ship</option>
                    </select>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="multiple_veh_info" class="form-label">Multiple Veh. Info (Optional)</label>
                    <textarea class="form-control" id="multiple_veh_info" name="multiple_veh_info" rows="1"><?= set_value('multiple_veh_info') ?></textarea>
                </div>
                <div class="col-md-6 mb-3">
                    <label for="cewb_no" class="form-label">CEWB No. (Optional)</label>
                    <input type="text" class="form-control" id="cewb_no" name="cewb_no" value="<?= set_value('cewb_no') ?>">
                </div>
            </div>

            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="transaction_type" class="form-label">Transaction Type</label>
                    <select class="form-control" id="transaction_type" name="transaction_type" required>
                        <option value="">Select Transaction Type</option>
                        <option value="Regular" <?= set_select('transaction_type', 'Regular') ?>>Regular</option>
                        <option value="Sales Return" <?= set_select('transaction_type', 'Sales Return') ?>>Sales Return</option>
                        <option value="Export" <?= set_select('transaction_type', 'Export') ?>>Export</option>
                        <option value="Other" <?= set_select('transaction_type', 'Other') ?>>Other</option>
                    </select>
                </div>
                <div class="col-md-6 mb-3">
                    <label for="reason_for_transportation" class="form-label">Reason for Transportation</label>
                    <textarea class="form-control" id="reason_for_transportation" name="reason_for_transportation" rows="1" required><?= set_value('reason_for_transportation') ?></textarea>
                </div>
            </div>

            <div class="d-flex justify-content-between mt-4">
                <button type="submit" class="btn btn-primary px-4">Save</button>
                <a href="<?= base_url('e-way-bills') ?>" class="btn btn-secondary px-4">Cancel</a>
            </div>
        </form>
    </div>
</div>

<?php $this->endSection(); ?>
