<?= $this->extend('layouts/main') ?>

<?= $this->section('content') ?>
<div class="container mt-4">
    <h1 class="mb-4"><?= esc($title) ?></h1>

    <?php if (session()->getFlashdata('success')): ?>
        <div class="alert alert-success"><?= session()->getFlashdata('success') ?></div>
    <?php endif; ?>

    <?php if (session()->getFlashdata('error')): ?>
        <div class="alert alert-danger"><?= session()->getFlashdata('error') ?></div>
    <?php endif; ?>

    <?php if (session()->getFlashdata('errors')): ?>
        <div class="alert alert-danger">
            <ul>
                <?php foreach (session()->getFlashdata('errors') as $error): ?>
                    <li><?= esc($error) ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>

    <form action="<?= base_url('e-way-bills/update/' . $eway_bill['id']) ?>" method="post">
        <?= csrf_field() ?>
        <input type="hidden" name="_method" value="PUT">

        <div class="card shadow-sm">
            <div class="card-body">
                <div class="row">
                    <!-- Sales Order Invoice Number -->
                    <div class="col-md-6 mb-3">
                        <label for="distributor_sales_order_id" class="form-label">Sales Order Invoice Number</label>
                        <select class="form-control" id="distributor_sales_order_id" name="distributor_sales_order_id" required>
                            <option value="">Select Sales Order</option>
                            <?php foreach ($sales_orders as $sales_order): ?>
                                <option
                                    value="<?= esc($sales_order['id']) ?>"
                                    data-invoice="<?= esc($sales_order['invoice_number'] ?? '') ?>"
                                    data-dispatch-place="<?= esc($sales_order['dispatch_place'] ?? '') ?>"
                                    data-delivery-place="<?= esc($sales_order['delivery_place'] ?? '') ?>"
                                    <?= ($sales_order['id'] == $eway_bill['distributor_sales_order_id']) ? 'selected' : '' ?>>
                                    <?= esc($sales_order['invoice_number'] ?? 'N/A') ?> - <?= esc($sales_order['agency_name']) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <!-- Bill Generated By -->
                    <div class="col-md-6 mb-3">
                        <label for="bill_generated_by" class="form-label">Bill Generated By</label>
                        <input type="text" class="form-control" id="bill_generated_by" name="bill_generated_by" value="<?= esc($eway_bill['bill_generated_by'] ?? '') ?>" required>
                    </div>

                    <!-- Place of Dispatch -->
                    <div class="col-md-6 mb-3">
                        <label for="place_of_dispatch" class="form-label">Place of Dispatch</label>
                        <input type="text" class="form-control" id="place_of_dispatch" name="place_of_dispatch" value="<?= esc($eway_bill['place_of_dispatch'] ?? '') ?>" required>
                    </div>

                    <!-- Place of Delivery -->
                    <div class="col-md-6 mb-3">
                        <label for="place_of_delivery" class="form-label">Place of Delivery</label>
                        <input type="text" class="form-control" id="place_of_delivery" name="place_of_delivery" value="<?= esc($eway_bill['place_of_delivery'] ?? '') ?>" required>
                    </div>

                    <!-- Driver Name -->
                    <div class="col-md-6 mb-3">
                        <label for="driver_name" class="form-label">Driver Name</label>
                        <input type="text" class="form-control" id="driver_name" name="driver_name" value="<?= esc($eway_bill['driver_name'] ?? '') ?>" required>
                    </div>

                    <!-- Vehicle Number -->
                    <div class="col-md-6 mb-3">
                        <!-- Changed name from 'vehicle_no' to 'vehicle_number' to match controller -->
                        <label for="vehicle_number" class="form-label">Vehicle Number</label>
                        <input type="text" class="form-control" id="vehicle_number" name="vehicle_number" value="<?= esc($eway_bill['vehicle_number'] ?? '') ?>" required>
                    </div>

                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="distance" class="form-label">Valid Distance (in KM)</label>
                            <input type="number" class="form-control" id="distance" name="distance" value="<?= esc($eway_bill['distance']) ?>" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="transport_mode" class="form-label">Transport Mode</label>
                            <select class="form-control" id="transport_mode" name="transport_mode" required>
                                <option value="Road" <?= ($eway_bill['transport_mode'] == 'Road') ? 'selected' : '' ?>>Road</option>
                                <option value="Rail" <?= ($eway_bill['transport_mode'] == 'Rail') ? 'selected' : '' ?>>Rail</option>
                                <option value="Air" <?= ($eway_bill['transport_mode'] == 'Air') ? 'selected' : '' ?>>Air</option>
                                <option value="Ship" <?= ($eway_bill['transport_mode'] == 'Ship') ? 'selected' : '' ?>>Ship</option>
                            </select>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="multiple_veh_info" class="form-label">Multiple Veh. Info (Optional)</label>
                            <!-- Removed 'required' attribute since it's an optional field -->
                            <input type="text" class="form-control" id="multiple_veh_info" name="multiple_veh_info" value="<?= esc($eway_bill['multiple_veh_info'] ?? '') ?>">
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="cewb_no" class="form-label">CEWB No. (Optional)</label>
                            <!-- Removed 'required' attribute since it's an optional field -->
                            <input type="text" class="form-control" id="cewb_no" name="cewb_no" value="<?= esc($eway_bill['cewb_no'] ?? '') ?>">
                        </div>
                    </div>

                    <!-- Transaction Type -->
                    <div class="col-md-6 mb-3">
                        <label for="transaction_type" class="form-label">Transaction Type</label>
                        <select class="form-control" id="transaction_type" name="transaction_type" required>
                            <option value="">Select Transaction Type</option>
                            <option value="Regular" <?= ($eway_bill['transaction_type'] == 'Regular') ? 'selected' : '' ?>>Regular</option>
                            <option value="Sales Return" <?= ($eway_bill['transaction_type'] == 'Sales Return') ? 'selected' : '' ?>>Sales Return</option>
                            <option value="Export" <?= ($eway_bill['transaction_type'] == 'Export') ? 'selected' : '' ?>>Export</option>
                            <option value="Other" <?= ($eway_bill['transaction_type'] == 'Other') ? 'selected' : '' ?>>Other</option>
                        </select>
                    </div>

                    <!-- Reason for Transportation -->
                    <div class="col-md-6 mb-3">
                        <label for="reason_for_transportation" class="form-label">Reason for Transportation</label>
                        <input type="text" class="form-control" id="reason_for_transportation" name="reason_for_transportation" value="<?= esc($eway_bill['reason_for_transportation'] ?? '') ?>" required>
                    </div>
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-primary mt-4">Update E-Way Bill</button>
        <a href="<?= base_url('e-way-bills') ?>" class="btn btn-secondary mt-4">Cancel</a>
    </form>
</div>
<?= $this->endSection() ?>
