    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <title>E-way Bill: <?= $eway_bill['eway_bill_no'] ?></title>
        <style>
            /* This font is necessary to display the rupee symbol correctly */
            body {
                font-family: 'DejaVu Sans', sans-serif;
                font-size: 12px;
                margin: 0;
                padding: 0;
            }

            .container {
                width: 90%;
                margin: 20px auto;
                border: 1px solid #000;
                padding: 0;
            }

            h1,
            h2 {
                text-align: center;
                margin: 0;
                padding: 0;
            }

            h1 {
                font-size: 20px;
                margin-bottom: 5px;
            }

            h2 {
                font-size: 16px;
                margin-bottom: 20px;
            }

            .header-section {
                padding: 20px 0;
                border-bottom: 1px solid #000;
            }

            /* New table styles for a structured layout */
            .info-table {
                width: 100%;
                border-collapse: collapse;
            }

            .info-table td {
                border: 1px solid #000;
                padding: 8px;
                vertical-align: top;
            }

            .info-label {
                font-weight: bold;
                width: 200px;
                background-color: #f7f7f7;
            }

            /* Styling for the Supplier/Recipient section */
            .two-column-layout {
                width: 100%;
                border-collapse: collapse;
            }

            .two-column-layout .info-table {
                border: none;
                width: 100%;
            }

            .two-column-layout td {
                border: none;
                padding: 0;
                width: 50%;
                /* Each column takes up half the width */
            }

            .two-column-layout .left-column {
                border-right: 1px solid #000;
                /* Add a divider line between the columns */
            }

            /* Products table */
            .product-table {
                width: 100%;
                border-collapse: collapse;
                margin-top: 20px;
            }

            .product-table th,
            .product-table td {
                border: 1px solid #000;
                padding: 8px;
                text-align: left;
            }

            .product-table th {
                background-color: #f8f8f8;
                font-weight: bold;
            }

            .text-right {
                text-align: right;
            }

            .total-value-row {
                border-top: 1px solid #000;
            }

            .total-value-cell {
                text-align: right;
                font-weight: bold;
                padding: 8px;
            }
        </style>
    </head>

    <body>

        <div class="container">
            <div class="header-section">
                <h1>E-WAY BILL</h1>

            </div>

            <!-- E-way Bill and Transport Details -->
            <table class="info-table">
                <tr>
                    <td class="info-label">E-Way Bill No:</td>
                    <td colspan="3"><?= esc($eway_bill['eway_bill_no']) ?></td>
                </tr>
                <tr>
                    <td class="info-label">E-Way Bill Date:</td>
                    <td colspan="3"><?= esc($eway_bill['generated_at']) ?></td>
                </tr>
                <tr>
                    <td class="info-label">Bill Generated By:</td>
                    <td colspan="3"><?= esc($eway_bill['bill_generated_by']) ?></td>
                </tr>
                <tr>
                    <td class="info-label">Valid From:</td>
                    <td colspan="3"><?= esc($eway_bill['generated_at']) ?></td>
                </tr>
                <tr>
                    <td class="info-label">Valid Until:</td>
                    <td colspan="3"><?= esc($eway_bill['valid_until']) ?></td>
                </tr>
                <tr>
                    <td class="info-label" style="border: none; background-color: transparent;"> Part A</td>
                    <td colspan="3" style="border-left: none; background-color: transparent;"> </td>
                </tr>
                <tr>

                    <td class="info-label">GSTIN Of Supplier</td>
                    <td colspan="3">37AQFPB2946M1ZN, SAMHITA SOIL SOLUTIONS </td>
                </tr>
                <tr>
                    <td class="info-label">Supplier Phone:</td>
                    <td colspan="3">9848549349, 9491822559</td>
                </tr>
                <tr>
                    <td class="info-label">Dispatch Of Place:</td>
                    <td colspan="3"><?= esc($eway_bill['place_of_dispatch']) ?></td>
                </tr>
                <tr>
                    <td class="info-label">GSTIN Of Recipient :</td>
                    <td colspan="3"><?= isset($distributor['agency_gst_number']) ? esc($distributor['agency_gst_number']) : 'N/A' ?> , <?= esc($distributor['agency_name']) ?></td>
                </tr>
                <tr>
                    <td class="info-label">Recipient Phone:</td>
                    <td colspan="3"><?= isset($distributor['owner_phone']) ? esc($distributor['owner_phone']) : '' ?>, <?= isset($distributor['agent_phone']) ? esc($distributor['agent_phone']) : '' ?></td>
                </tr>
                <tr>

                    <td class="info-label"> Place Of Delivery:</td>
                    <td colspan="3"><?= esc($eway_bill['place_of_delivery']) ?></td>

                </tr>
                <tr>
                    <td class="info-label">Transaction Type:</td>
                    <td colspan="3"><?= esc($eway_bill['transaction_type']) ?></td>
                </tr>
                <tr>
                    <td class="info-label">Values Of Goods</td>
                    <td colspan="3">₹<?= number_format($sales_order['final_total_amount'], 2) ?></td>
                </tr>

                <tr>
                    <td class="info-label">Reason for Transportation:</td>
                    <td colspan="3"><?= esc($eway_bill['reason_for_transportation']) ?></td>
                </tr>

                <tr>
                    <td class="info-label">Product Details:</td>
                    <td colspan="3">
                        <?php foreach ($sales_order_items as $item): ?>
                            <?= esc($item['name']) ?> ,
                        <?php endforeach; ?>

                    </td>
                </tr>




                <tr>
                    <td class="info-label" style="border: none; background-color: transparent;"> Part B</td>
                    <td colspan="3" style="border-left: none; background-color: transparent;"> </td>
                </tr>

                <tr>
                    <td class="info-label">Driver Name:</td>
                    <td colspan="3"><?= esc($eway_bill['driver_name']) ?></td>
                </tr>

<tr>
                    <td class="info-label">Vechicle No:</td>
                    <td colspan="3"><?= esc($eway_bill['vehicle_number']) ?></td>
                </tr>
            </table>




            <!-- Products in Shipment -->
            <table class="product-table">
                <thead>
                    <tr>
                        <th class="text-right">Transport Mode</th>
                        <th class="text-right">From</th>
                        <th class="text-right">Distance</th>
                        <th class="text-right">CEWB No. <br> (IF ANY)</th>
                        <th class="text-right">Multi Veh.Info <br> (IF ANY)</th>
                  
                    </tr>
                </thead>
                <tbody>
                   
                        <tr>
                            <td colspan="1"><?= esc($eway_bill['transport_mode']) ?></td>
                            <td colspan="1"><?= esc($eway_bill['place_of_dispatch']) ?></td>
                            <td colspan="1"><?= esc($eway_bill['distance']) ?> Km</td>
                            <td colspan="1"><?= esc($eway_bill['cewb_no']) ?></td>
                            <td colspan="1"><?= esc($eway_bill['multiple_veh_info']) ?></td>
                        </tr>
                     

                </tbody>
            </table>

        </div>

    </body>

    </html>