<?= $this->extend('layouts/main'); ?>

<?php $this->section('content'); ?>

<div class="container my-5">
    <!-- Page Header and Actions -->
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h2><?= esc($title) ?></h2>
        <div>
            <!-- Replaced the Print button with a link to download the PDF -->
            <a href="<?= base_url('e-way-bills/download-pdf/' . $eway_bill['id']) ?>" class="btn btn-primary" target="_blank">
                <i class="fas fa-file-pdf"></i> Save as PDF
            </a>
            <a href="<?= base_url('e-way-bills') ?>" class="btn btn-secondary">Back to List</a>
        </div>
    </div>

    <!-- Main E-way Bill Details Card -->
    <div class="card mb-4 shadow-sm">
        <div class="card-header bg-primary text-white">
            <h4 class="mb-0">E-way Bill: #<?= esc($eway_bill['eway_bill_no']) ?></h4>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <p class="mb-1"><strong>Invoice Number:</strong> <?= esc($sales_order['invoice_number']) ?></p>
                    <p class="mb-1"><strong>Reason for Transportation:</strong> <?= esc($eway_bill['reason_for_transportation']) ?></p>
                    <p class="mb-1"><strong>Transaction Type:</strong> <?= esc($eway_bill['transaction_type']) ?></p>

                </div>
                <div class="col-md-6">
                    <p class="mb-1"><strong>Bill Generated By:</strong> <?= esc($eway_bill['bill_generated_by']) ?></p>
                    <p class="mb-1"><strong>Dispatch Place:</strong> <?= esc($eway_bill['place_of_dispatch']) ?></p>
                    <p class="mb-1"><strong>Delivery Place:</strong> <?= esc($eway_bill['place_of_delivery']) ?></p>
                </div>
            </div>
        </div>
    </div>


    <div class="row mb-4">

        <div class="col-md-6">
            <div class="card h-100 shadow-sm">
                <div class="card-header">
                    <h5 class="mb-0">Transport Details</h5>
                </div>
                <div class="card-body">
                    <p class="mb-1"><strong>Driver Name:</strong> <?= esc($eway_bill['driver_name']) ?></p>
                    <p class="mb-1"><strong>Vehicle Number:</strong> <?= esc($eway_bill['vehicle_number']) ?></p>
                    <p class="mb-1"><strong>Transport Mode:</strong> <?= esc($eway_bill['transport_mode']) ?></p>
                    <p class="mb-1"><strong>Multi Veh. Info:</strong> <?= esc($eway_bill['multiple_veh_info']) ?></p>
                </div>
            </div>
        </div>


        <div class="col-md-6">
            <div class="card h-100 shadow-sm">
                <div class="card-header">
                    <h5 class="mb-0">Bill Valid</h5>
                </div>
                <div class="card-body">
                    <p class="mb-1"><strong>Generated At:</strong> <?= esc($eway_bill['generated_at']) ?></p>
                    <p class="mb-1"><strong>Valid Until:</strong> <?= esc($eway_bill['valid_until']) ?></p>
                    <p class="mb-1"><strong>Distance Valid  :</strong> <?= esc($eway_bill['distance']) ?> Km</p>
                    <p class="mb-1"><strong>CEWB No.  :</strong> <?= esc($eway_bill['cewb_no']) ?>  </p>
                </div>
            </div>
        </div>
    </div>

    <!-- Supplier & Recipient Details -->
    <div class="row mb-4">
        <!-- Supplier Card -->
        <div class="col-md-6">
            <div class="card h-100 shadow-sm">
                <div class="card-header">
                    <h5 class="mb-0">Supplier Details</h5>
                </div>
                <div class="card-body">
                    <p class="mb-1"><strong>Name:</strong> SAMHITA SOIL SOLUTIONS</p>
                    <p class="mb-1"><strong>GSTIN:</strong> 37AQFPB2946M1ZN</p>
                    <p class="mb-1"><strong>Phone:</strong> 9848549349, 9491822559</p>
                    <p class="mb-1"><strong>Email:</strong> samhithasoilsolutions@gmail.com</p>
                    <p class="mb-1"><strong>Address:</strong> 2-46-26/21, Venkat Nager, Kakinada-533003</p>
                </div>
            </div>
        </div>

        <!-- Recipient Card -->
        <div class="col-md-6">
            <div class="card h-100 shadow-sm">
                <div class="card-header">
                    <h5 class="mb-0">Recipient Details</h5>
                </div>
                <div class="card-body">
                    <p class="mb-1"><strong>Agency Name:</strong> <?= esc($distributor['agency_name']) ?></p>
                    <p class="mb-1"><strong>GSTIN:</strong> <?= isset($distributor['agency_gst_number']) ? esc($distributor['agency_gst_number']) : 'N/A' ?></p>
                    <p class="mb-1"><strong>Phone:</strong> <?= isset($distributor['owner_phone']) ? esc($distributor['owner_phone']) : '' ?>,  <?= isset($distributor['agent_phone']) ? esc($distributor['agent_phone']) : '' ?></p>
                    <p class="mb-1"><strong>Email:</strong> <?= isset($distributor['gmail']) ? esc($distributor['gmail']) : 'N/A' ?></p>
                    <p class="mb-1"><strong>Address:</strong> <?= isset($distributor['agency_address']) ? esc($distributor['agency_address']) : 'N/A' ?></p>
                </div>
            </div>
        </div>
    </div>

    <!-- Products & Value Card -->
    <div class="card shadow-sm">
        <div class="card-header">
            <h5 class="mb-0">Products in Shipment</h5>
        </div>
        <div class="card-body">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Product Name</th>
                        <th class="text-end">Quantity</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($sales_order_items as $item): ?>
                        <tr>
                            <td><?= esc($item['name']) ?></td>
                            <td class="text-end"><?= esc($item['quantity']) ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <div class="d-flex justify-content-end mt-3">
                <p class="h5"><strong>Total Value:</strong> ₹<?= number_format($sales_order['final_total_amount'], 2) ?></p>
            </div>
        </div>
    </div>

</div>

<?php $this->endSection(); ?>
